### ISSUE TITLE
Provide in-IDE popup documentation for XQuery API functions and parameters

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#11]

**Comment by ronhitchens** [comment]
This is done so far as bringing the function pop-up doc code into the new plugin and displaying the API docs.  It has been enhanced as well to include more fields and better formatting.

However, the XML file from which it's driven is quite old (ML 5.x).  Creating another ticket for updating the IDE function docs from a newer version (8.x) of the ML docs).

**Comment by ronhitchens** [comment]
This is complete now, and Issue #15 has been completed so that the latest MarkLogic 8 documentation is available in the plugin.

This can be tested by installing the plugin and then opening a project with XQuery source files.  Find, or create, a reference to a MarkLogic-specific or W3C standard function.  This must be a function that is recognized by the plugin (not all MarkLogic 8 functions are, yet).  Place the cursor on the name of the function and select the View > Quick Documentation function (or the equivalent hotkey).  A small yellow window should pop up with the relevant API information, very similar to the corresponding API doc page on the MarkLogic developer site.  Selecting Quick Documentation again will expand the pop-up window to a bigger size.  The API info displayed should match up with the ML docs page, though the order and formatting will be somewhat different.

**Comment by ronhitchens** [comment]
This was addressed in version 0.9.0-beta
