### ISSUE TITLE
Create CI/Build pipeline

### ISSUE THREAD

**Issue by chrisrhayes** [overstory/marklogic-intellij-plugin#2]
- [x] Analyse existing Travis build capability
- [x] Select CI tool
- [x] Configure build tool
- [ ] Configure docker image

**Comment by ronhitchens** [comment]
I looked into this a bit and determined that the Travis build tool, which is similar to shippable.com, is free to use for open source projects.  So I registered with it so that it now runs on each commit and updates the badge on the project home page.  More info at [travis-ci.org](https://travis-ci.org/).

Currently the minimum integration is in place, and the automated tests from the original repo are now all passing.  But the build is running now.  Further tweaks and notifications should be setup.

**Comment by ronhitchens** [comment]
This is working, closing.
